server {
    listen 80 default_server;
    server_name _;

    root /app/bbuddy;
    index index.php index.html;
    server_tokens off;

    access_log /dev/stdout;
    error_log /dev/stderr warn;

    client_max_body_size 100M;
    client_body_buffer_size 128k;

    location / {
        try_files $uri $uri/ =404;
    }

    location /api/ {
        try_files $uri /api/index.php$is_args$query_string;
    }

    location ~ ^/(?:data|example)(?:/|$) {
        deny all;
    }

    location ~ /\. {
        deny all;
    }

    location ~ \.php$ {
        try_files $uri =404;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param HTTP_PROXY "";
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_read_timeout 80s;
        fastcgi_buffering off;
        fastcgi_pass_header X-Accel-Buffering;
    }
}
