[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
pidfile=/run/supervisord.pid
user=root

[program:redis]
command=/usr/bin/redis-server --bind 127.0.0.1 --protected-mode yes --save "" --appendonly no
user=redis
priority=10
autostart=true
autorestart=true
startsecs=2
stopasgroup=true
killasgroup=true
redirect_stderr=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0

[program:php-fpm]
command=/usr/sbin/php-fpm83 --nodaemonize --fpm-config /etc/php83/php-fpm.conf
user=root
priority=20
autostart=true
autorestart=true
startsecs=2
stopasgroup=true
killasgroup=true
redirect_stderr=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
user=root
priority=30
autostart=true
autorestart=true
startsecs=2
stopasgroup=true
killasgroup=true
redirect_stderr=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0

[program:websocket]
command=/usr/bin/php83 /app/bbuddy/wsserver.php
user=barcodebuddy
priority=30
autostart=true
autorestart=true
startsecs=2
startretries=10
stopasgroup=true
killasgroup=true
redirect_stderr=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0

[program:cron]
command=/usr/local/bin/barcodebuddy-cron
user=barcodebuddy
priority=30
autostart=true
autorestart=true
startsecs=2
stopasgroup=true
killasgroup=true
redirect_stderr=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0

[include]
files=/etc/supervisor.d/*.ini
